# Auto-generated Alembic migration script template
#
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e4ffe2a3e641'
down_revision = '035'
branch_labels = None
depends_on = None


def upgrade():
    """Write your upgrade migrations here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_webhook_events_created_at'), table_name='webhook_events')
    op.drop_index(op.f('idx_webhook_events_event_id'), table_name='webhook_events')
    op.drop_index(op.f('idx_webhook_events_processed_at'), table_name='webhook_events')
    op.drop_index(op.f('idx_webhook_events_source_type'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('idx_ingestion_dedup_is_dup'), table_name='ingestion_deduplication')
    op.drop_index(op.f('idx_ingestion_dedup_run_row'), table_name='ingestion_deduplication')
    op.drop_index(op.f('idx_ingestion_dedup_uuid'), table_name='ingestion_deduplication')
    op.drop_index(op.f('ix_ingestion_deduplication_beast_uuid'), table_name='ingestion_deduplication')
    op.drop_index(op.f('ix_ingestion_deduplication_is_duplicate'), table_name='ingestion_deduplication')
    op.drop_table('ingestion_deduplication')
    op.drop_index(op.f('idx_failed_email_queue_created_at'), table_name='failed_email_queue')
    op.drop_index(op.f('idx_failed_email_queue_task_next_retry'), table_name='failed_email_queue')
    op.drop_table('failed_email_queue')
    op.drop_index(op.f('idx_gmail_audit_log_created_at'), table_name='gmail_credential_audit_log')
    op.drop_index(op.f('idx_gmail_audit_log_event_type'), table_name='gmail_credential_audit_log')
    op.drop_index(op.f('idx_gmail_audit_log_task_id'), table_name='gmail_credential_audit_log')
    op.drop_table('gmail_credential_audit_log')
    op.drop_index(op.f('idx_gmail_credential_status_status'), table_name='gmail_credential_status')
    op.drop_index(op.f('idx_gmail_credential_status_task_id'), table_name='gmail_credential_status')
    op.drop_table('gmail_credential_status')
    op.drop_index(op.f('idx_tag_feedback_article_id'), table_name='tag_feedback')
    op.drop_index(op.f('idx_tag_feedback_recorded_at'), table_name='tag_feedback')
    op.drop_index(op.f('idx_tag_feedback_tag_slug'), table_name='tag_feedback')
    op.drop_table('tag_feedback')
    op.drop_index(op.f('idx_tags_is_primary'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('idx_ingestion_tasks_adaptor_type'), table_name='ingestion_tasks')
    op.drop_index(op.f('idx_ingestion_tasks_created_by'), table_name='ingestion_tasks')
    op.drop_index(op.f('idx_ingestion_tasks_status'), table_name='ingestion_tasks')
    op.drop_index(op.f('idx_ingestion_tasks_test_enabled'), table_name='ingestion_tasks')
    op.drop_table('ingestion_tasks')
    op.drop_index(op.f('idx_time_of_day_metrics_created_at'), table_name='time_of_day_metrics')
    op.drop_index(op.f('idx_time_of_day_metrics_day_of_week'), table_name='time_of_day_metrics')
    op.drop_index(op.f('idx_time_of_day_metrics_hour_platform'), table_name='time_of_day_metrics')
    op.drop_index(op.f('idx_time_of_day_metrics_metric_name'), table_name='time_of_day_metrics')
    op.drop_table('time_of_day_metrics')
    op.drop_index(op.f('idx_dataset_files_dataset_id'), table_name='dataset_files')
    op.drop_index(op.f('idx_dataset_files_embed_status'), table_name='dataset_files')
    op.drop_index(op.f('idx_dataset_files_uploaded_at'), table_name='dataset_files')
    op.drop_table('dataset_files')
    op.drop_index(op.f('idx_conversations_updated_at'), table_name='conversations')
    op.drop_index(op.f('idx_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('idx_schema_mapping_templates_created_by'), table_name='schema_mapping_templates')
    op.drop_index(op.f('idx_schema_mapping_templates_name'), table_name='schema_mapping_templates')
    op.drop_table('schema_mapping_templates')
    op.drop_index(op.f('idx_app_settings_is_secret'), table_name='app_settings')
    op.drop_index(op.f('idx_app_settings_updated_at'), table_name='app_settings')
    op.drop_table('app_settings')
    op.drop_index(op.f('idx_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('idx_messages_created_at'), table_name='messages')
    op.drop_index(op.f('idx_messages_sequence'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('idx_summaries_granularity'), table_name='summaries')
    op.drop_index(op.f('idx_summaries_metric_name'), table_name='summaries')
    op.drop_index(op.f('idx_summaries_period'), table_name='summaries')
    op.drop_index(op.f('idx_summaries_platform'), table_name='summaries')
    op.drop_index(op.f('idx_summaries_unique'), table_name='summaries')
    op.drop_table('summaries')
    op.drop_index(op.f('idx_datasets_created_at'), table_name='datasets')
    op.drop_index(op.f('idx_datasets_slug'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('idx_article_vectors_article_id'), table_name='article_vectors')
    op.drop_index(op.f('idx_article_vectors_created_at'), table_name='article_vectors')
    op.drop_index(op.f('idx_article_vectors_deleted_at'), table_name='article_vectors')
    op.drop_index(op.f('idx_article_vectors_hnsw'), table_name='article_vectors', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_table('article_vectors')
    op.drop_index(op.f('idx_users_auth_provider'), table_name='users')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_is_active'), table_name='users')
    op.drop_index(op.f('idx_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('idx_task_schema_mappings_task_id'), table_name='task_schema_mappings')
    op.drop_index(op.f('idx_task_schema_mappings_template_id'), table_name='task_schema_mappings')
    op.drop_table('task_schema_mappings')
    op.drop_index(op.f('idx_cron_test_runs_executed_at'), table_name='cron_test_runs')
    op.drop_index(op.f('idx_cron_test_runs_task_executed'), table_name='cron_test_runs')
    op.drop_index(op.f('idx_cron_test_runs_task_id'), table_name='cron_test_runs')
    op.drop_table('cron_test_runs')
    op.drop_index(op.f('idx_password_reset_tokens_expires_at'), table_name='password_reset_tokens')
    op.drop_index(op.f('idx_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('idx_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.drop_index(op.f('documents_author_name_idx'), table_name='documents')
    op.drop_index(op.f('documents_content_type_idx'), table_name='documents')
    op.drop_index(op.f('documents_embedding_idx'), table_name='documents', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('documents_labels_idx'), table_name='documents')
    op.drop_index(op.f('documents_media_type_idx'), table_name='documents')
    op.drop_index(op.f('documents_platform_idx'), table_name='documents')
    op.drop_index(op.f('documents_profile_name_idx'), table_name='documents')
    op.drop_index(op.f('documents_published_date_idx'), table_name='documents')
    op.drop_index(op.f('documents_total_interactions_idx'), table_name='documents')
    op.drop_index(op.f('documents_unique_current_key'), table_name='documents', postgresql_where='(is_current IS TRUE)')
    op.drop_index(op.f('documents_video_views_idx'), table_name='documents')
    op.drop_index(op.f('idx_documents_beast_uuid'), table_name='documents')
    op.drop_index(op.f('idx_documents_identifier_cleaned'), table_name='documents')
    op.drop_index(op.f('idx_documents_identifier_hash'), table_name='documents')
    op.drop_index(op.f('idx_documents_metric_deltas'), table_name='documents', postgresql_using='gin')
    op.drop_index(op.f('idx_documents_s3_key'), table_name='documents')
    op.drop_index(op.f('idx_documents_sheet_row_current'), table_name='documents')
    op.drop_index(op.f('ix_documents_connection_identifier_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('idx_agent_messages_session_time'), table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index(op.f('idx_processed_emails_message_id'), table_name='processed_emails')
    op.drop_index(op.f('idx_processed_emails_processed_at'), table_name='processed_emails')
    op.drop_index(op.f('idx_processed_emails_task_id'), table_name='processed_emails')
    op.drop_table('processed_emails')
    op.drop_index(op.f('idx_uploaded_files_created_at'), table_name='uploaded_files')
    op.drop_index(op.f('idx_uploaded_files_run_id'), table_name='uploaded_files')
    op.drop_index(op.f('idx_uploaded_files_s3_key'), table_name='uploaded_files')
    op.drop_index(op.f('idx_uploaded_files_task_id'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index(op.f('idx_ingestion_task_runs_created_at'), table_name='ingestion_task_runs')
    op.drop_index(op.f('idx_ingestion_task_runs_error_type'), table_name='ingestion_task_runs')
    op.drop_index(op.f('idx_ingestion_task_runs_status'), table_name='ingestion_task_runs')
    op.drop_index(op.f('idx_ingestion_task_runs_task_id'), table_name='ingestion_task_runs')
    op.drop_index(op.f('ix_ingestion_task_runs_celery_task_id'), table_name='ingestion_task_runs')
    op.drop_index(op.f('ix_ingestion_task_runs_parent_run_id_task_id'), table_name='ingestion_task_runs')
    op.drop_table('ingestion_task_runs')
    op.drop_table('agent_sessions')
    # ### end Alembic commands ###


def downgrade():
    """Write your downgrade migrations here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_sessions',
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('session_id', name=op.f('agent_sessions_pkey'))
    )
    op.create_table('ingestion_task_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('rows_inserted', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('rows_updated', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('rows_failed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('run_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('error_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('error_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('total_rows_processed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_duplicates_found', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_deltas_calculated', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('deduplication_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('failed_emails_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='Number of emails that failed processing during this run'),
    sa.Column('retry_emails_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='Number of emails queued for retry after this run'),
    sa.Column('parent_run_id', sa.UUID(), autoincrement=False, nullable=True, comment='Foreign key to parent task run (for sub-task hierarchies)'),
    sa.Column('celery_task_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_run_id'], ['ingestion_task_runs.id'], name=op.f('fk_ingestion_task_runs_parent_run_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['ingestion_tasks.id'], name=op.f('ingestion_task_runs_task_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ingestion_task_runs_pkey'))
    )
    op.create_index(op.f('ix_ingestion_task_runs_parent_run_id_task_id'), 'ingestion_task_runs', ['parent_run_id', 'task_id'], unique=False)
    op.create_index(op.f('ix_ingestion_task_runs_celery_task_id'), 'ingestion_task_runs', ['celery_task_id'], unique=False)
    op.create_index(op.f('idx_ingestion_task_runs_task_id'), 'ingestion_task_runs', ['task_id'], unique=False)
    op.create_index(op.f('idx_ingestion_task_runs_status'), 'ingestion_task_runs', ['status'], unique=False)
    op.create_index(op.f('idx_ingestion_task_runs_error_type'), 'ingestion_task_runs', ['error_type'], unique=False)
    op.create_index(op.f('idx_ingestion_task_runs_created_at'), 'ingestion_task_runs', ['created_at'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('s3_key', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_task_runs.id'], name=op.f('uploaded_files_run_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['ingestion_tasks.id'], name=op.f('uploaded_files_task_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('uploaded_files_pkey')),
    sa.UniqueConstraint('s3_key', name=op.f('uploaded_files_s3_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_uploaded_files_task_id'), 'uploaded_files', ['task_id'], unique=False)
    op.create_index(op.f('idx_uploaded_files_s3_key'), 'uploaded_files', ['s3_key'], unique=False)
    op.create_index(op.f('idx_uploaded_files_run_id'), 'uploaded_files', ['run_id'], unique=False)
    op.create_index(op.f('idx_uploaded_files_created_at'), 'uploaded_files', ['created_at'], unique=False)
    op.create_table('processed_emails',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sender', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rows_inserted', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rows_skipped', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rows_failed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_success', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False, comment='Whether email was successfully processed (all rows succeeded or had rows at all)'),
    sa.Column('is_retryable', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='Whether email can/should be retried'),
    sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Original sent date/time from the email headers'),
    sa.Column('rows_updated', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='Rows appended/updated from this email'),
    sa.PrimaryKeyConstraint('id', name=op.f('processed_emails_pkey')),
    sa.UniqueConstraint('message_id', name=op.f('processed_emails_message_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_processed_emails_task_id'), 'processed_emails', ['task_id'], unique=False)
    op.create_index(op.f('idx_processed_emails_processed_at'), 'processed_emails', ['processed_at'], unique=False)
    op.create_index(op.f('idx_processed_emails_message_id'), 'processed_emails', ['message_id'], unique=True)
    op.create_table('agent_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.session_id'], name=op.f('agent_messages_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_messages_pkey'))
    )
    op.create_index(op.f('idx_agent_messages_session_time'), 'agent_messages', ['session_id', 'created_at'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sheet_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('row_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('doc_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('published_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('received_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('profile_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('profile_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('profile_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('post_detail_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('platform', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('media_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('origin_of_the_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('author_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('author_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('link_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('view_on_platform', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('organic_interactions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_interactions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_reactions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_comments', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_shares', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unpublished', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('engagements', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_reach', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('paid_reach', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('organic_reach', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_impressions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('paid_impressions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('organic_impressions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reach_engagement_rate', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('total_likes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('video_length_sec', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('video_views', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_video_view_time_sec', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_video_view_time_sec', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('completion_rate', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('labels', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('label_groups', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('reported_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('is_current', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('beast_uuid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('identifier_cleaned', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('identifier_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('metric_deltas', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('published_time', postgresql.TIME(), autoincrement=False, nullable=True, comment='Time component of publication (complements published_date)'),
    sa.Column('connection_identifier_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True, comment='SHA256 hash of normalized connection_strategy value for cross-platform matching'),
    sa.Column('s3_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('s3_key', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_pkey'))
    )
    op.create_index(op.f('ix_documents_connection_identifier_hash'), 'documents', ['connection_identifier_hash'], unique=False)
    op.create_index(op.f('idx_documents_sheet_row_current'), 'documents', ['sheet_name', 'row_number', 'is_current'], unique=False)
    op.create_index(op.f('idx_documents_s3_key'), 'documents', ['s3_key'], unique=False)
    op.create_index(op.f('idx_documents_metric_deltas'), 'documents', ['metric_deltas'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_documents_identifier_hash'), 'documents', ['identifier_hash', 'is_current'], unique=False)
    op.create_index(op.f('idx_documents_identifier_cleaned'), 'documents', ['identifier_cleaned'], unique=False)
    op.create_index(op.f('idx_documents_beast_uuid'), 'documents', ['beast_uuid'], unique=False)
    op.create_index(op.f('documents_video_views_idx'), 'documents', ['video_views'], unique=False)
    op.create_index(op.f('documents_unique_current_key'), 'documents', ['sheet_name', 'row_number'], unique=True, postgresql_where='(is_current IS TRUE)')
    op.create_index(op.f('documents_total_interactions_idx'), 'documents', ['total_interactions'], unique=False)
    op.create_index(op.f('documents_published_date_idx'), 'documents', ['published_date'], unique=False)
    op.create_index(op.f('documents_profile_name_idx'), 'documents', ['profile_name'], unique=False)
    op.create_index(op.f('documents_platform_idx'), 'documents', ['platform'], unique=False)
    op.create_index(op.f('documents_media_type_idx'), 'documents', ['media_type'], unique=False)
    op.create_index(op.f('documents_labels_idx'), 'documents', ['labels'], unique=False)
    op.create_index(op.f('documents_embedding_idx'), 'documents', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('documents_content_type_idx'), 'documents', ['content_type'], unique=False)
    op.create_index(op.f('documents_author_name_idx'), 'documents', ['author_name'], unique=False)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('used', sa.CHAR(length=1), server_default=sa.text("'N'::bpchar"), autoincrement=False, nullable=False),
    sa.CheckConstraint("used = ANY (ARRAY['Y'::bpchar, 'N'::bpchar])", name=op.f('password_reset_tokens_used_check')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('password_reset_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('password_reset_tokens_pkey')),
    sa.UniqueConstraint('token', name=op.f('password_reset_tokens_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index(op.f('idx_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=False)
    op.create_index(op.f('idx_password_reset_tokens_expires_at'), 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_table('cron_test_runs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('executed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('logs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['ingestion_tasks.id'], name=op.f('cron_test_runs_task_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('cron_test_runs_pkey'))
    )
    op.create_index(op.f('idx_cron_test_runs_task_id'), 'cron_test_runs', ['task_id'], unique=False)
    op.create_index(op.f('idx_cron_test_runs_task_executed'), 'cron_test_runs', ['task_id', 'executed_at'], unique=False)
    op.create_index(op.f('idx_cron_test_runs_executed_at'), 'cron_test_runs', ['executed_at'], unique=False)
    op.create_table('task_schema_mappings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('template_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('source_columns', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('field_mappings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('identifier_column', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('dedup_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Deduplication strategy config: {default_strategy, field_strategies, is_metric}'),
    sa.Column('connection_strategy_identifier_column', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Column name for cross-platform content matching (e.g., article_title, video_description)'),
    sa.ForeignKeyConstraint(['task_id'], ['ingestion_tasks.id'], name=op.f('task_schema_mappings_task_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['schema_mapping_templates.id'], name=op.f('task_schema_mappings_template_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('task_schema_mappings_pkey')),
    sa.UniqueConstraint('task_id', name=op.f('task_schema_mappings_task_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_task_schema_mappings_template_id'), 'task_schema_mappings', ['template_id'], unique=False)
    op.create_index(op.f('idx_task_schema_mappings_task_id'), 'task_schema_mappings', ['task_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('auth_provider', sa.VARCHAR(length=50), server_default=sa.text("'local'::character varying"), autoincrement=False, nullable=False),
    sa.Column('ad_username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('users_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('idx_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('idx_users_auth_provider'), 'users', ['auth_provider'], unique=False)
    op.create_table('article_vectors',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('article_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('article_vectors_pkey')),
    sa.UniqueConstraint('article_id', name=op.f('article_vectors_article_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_article_vectors_hnsw'), 'article_vectors', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('idx_article_vectors_deleted_at'), 'article_vectors', ['deleted_at'], unique=False)
    op.create_index(op.f('idx_article_vectors_created_at'), 'article_vectors', ['created_at'], unique=False)
    op.create_index(op.f('idx_article_vectors_article_id'), 'article_vectors', ['article_id'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('allowed_extensions', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('datasets_pkey')),
    sa.UniqueConstraint('slug', name=op.f('datasets_slug_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_datasets_slug'), 'datasets', ['slug'], unique=False)
    op.create_index(op.f('idx_datasets_created_at'), 'datasets', ['created_at'], unique=False)
    op.create_table('summaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('granularity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('period_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('period_end', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('metric_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('metric_value', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('metadata', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('summaries_pkey'))
    )
    op.create_index(op.f('idx_summaries_unique'), 'summaries', ['granularity', 'period_start', 'platform', 'metric_name'], unique=True)
    op.create_index(op.f('idx_summaries_platform'), 'summaries', ['platform'], unique=False)
    op.create_index(op.f('idx_summaries_period'), 'summaries', ['period_start', 'period_end'], unique=False)
    op.create_index(op.f('idx_summaries_metric_name'), 'summaries', ['metric_name'], unique=False)
    op.create_index(op.f('idx_summaries_granularity'), 'summaries', ['granularity'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('operation', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('operation_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('operation_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('sequence_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint("role::text = ANY (ARRAY['user'::character varying, 'assistant'::character varying]::text[])", name=op.f('messages_role_check')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('messages_conversation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('idx_messages_sequence'), 'messages', ['conversation_id', 'sequence_number'], unique=False)
    op.create_index(op.f('idx_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('idx_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('app_settings',
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_secret', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('app_settings_pkey'))
    )
    op.create_index(op.f('idx_app_settings_updated_at'), 'app_settings', ['updated_at'], unique=False)
    op.create_index(op.f('idx_app_settings_is_secret'), 'app_settings', ['is_secret'], unique=False)
    op.create_table('schema_mapping_templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_columns', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('field_mappings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('schema_mapping_templates_created_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('schema_mapping_templates_pkey')),
    sa.UniqueConstraint('name', name=op.f('schema_mapping_templates_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_schema_mapping_templates_name'), 'schema_mapping_templates', ['name'], unique=False)
    op.create_index(op.f('idx_schema_mapping_templates_created_by'), 'schema_mapping_templates', ['created_by'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('conversations_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('conversations_pkey'))
    )
    op.create_index(op.f('idx_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_index(op.f('idx_conversations_updated_at'), 'conversations', [sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('dataset_files',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dataset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('s3_key', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('file_size_bytes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('embed_status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('embed_task_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('chunks_created', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('dataset_files_dataset_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('dataset_files_pkey'))
    )
    op.create_index(op.f('idx_dataset_files_uploaded_at'), 'dataset_files', ['uploaded_at'], unique=False)
    op.create_index(op.f('idx_dataset_files_embed_status'), 'dataset_files', ['embed_status'], unique=False)
    op.create_index(op.f('idx_dataset_files_dataset_id'), 'dataset_files', ['dataset_id'], unique=False)
    op.create_table('time_of_day_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hour_of_day', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day_of_week', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metric_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('metric_value', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('sample_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('time_of_day_metrics_pkey'))
    )
    op.create_index(op.f('idx_time_of_day_metrics_metric_name'), 'time_of_day_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('idx_time_of_day_metrics_hour_platform'), 'time_of_day_metrics', ['hour_of_day', 'platform'], unique=False)
    op.create_index(op.f('idx_time_of_day_metrics_day_of_week'), 'time_of_day_metrics', ['day_of_week'], unique=False)
    op.create_index(op.f('idx_time_of_day_metrics_created_at'), 'time_of_day_metrics', ['created_at'], unique=False)
    op.create_table('ingestion_tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('adaptor_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('adaptor_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('schedule_type', sa.VARCHAR(length=50), server_default=sa.text("'none'::character varying"), autoincrement=False, nullable=False),
    sa.Column('cron_expression', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('run_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('test_execution_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('test_execution_interval_minutes', sa.INTEGER(), server_default=sa.text('60'), autoincrement=False, nullable=False),
    sa.Column('deduplication_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('dedup_lookback_imports', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('ingestion_tasks_created_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('ingestion_tasks_pkey'))
    )
    op.create_index(op.f('idx_ingestion_tasks_test_enabled'), 'ingestion_tasks', ['test_execution_enabled'], unique=False)
    op.create_index(op.f('idx_ingestion_tasks_status'), 'ingestion_tasks', ['status'], unique=False)
    op.create_index(op.f('idx_ingestion_tasks_created_by'), 'ingestion_tasks', ['created_by'], unique=False)
    op.create_index(op.f('idx_ingestion_tasks_adaptor_type'), 'ingestion_tasks', ['adaptor_type'], unique=False)
    op.create_table('tags',
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('variations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_primary', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('slug', name=op.f('tags_pkey'))
    )
    op.create_index(op.f('idx_tags_is_primary'), 'tags', ['is_primary'], unique=False)
    op.create_table('tag_feedback',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('article_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tag_slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('was_kept', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tag_feedback_pkey'))
    )
    op.create_index(op.f('idx_tag_feedback_tag_slug'), 'tag_feedback', ['tag_slug'], unique=False)
    op.create_index(op.f('idx_tag_feedback_recorded_at'), 'tag_feedback', ['recorded_at'], unique=False)
    op.create_index(op.f('idx_tag_feedback_article_id'), 'tag_feedback', ['article_id'], unique=False)
    op.create_table('gmail_credential_status',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('health_score', sa.INTEGER(), server_default=sa.text('100'), autoincrement=False, nullable=False),
    sa.Column('account_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('scopes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_auth_attempt_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('auth_established_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('token_refreshed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_error_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('consecutive_failures', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('max_consecutive_failures', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['ingestion_tasks.id'], name=op.f('gmail_credential_status_task_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('gmail_credential_status_pkey')),
    sa.UniqueConstraint('task_id', name=op.f('gmail_credential_status_task_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_gmail_credential_status_task_id'), 'gmail_credential_status', ['task_id'], unique=False)
    op.create_index(op.f('idx_gmail_credential_status_status'), 'gmail_credential_status', ['status'], unique=False)
    op.create_table('gmail_credential_audit_log',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('account_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('error_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('action_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['ingestion_tasks.id'], name=op.f('gmail_credential_audit_log_task_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('gmail_credential_audit_log_pkey'))
    )
    op.create_index(op.f('idx_gmail_audit_log_task_id'), 'gmail_credential_audit_log', ['task_id'], unique=False)
    op.create_index(op.f('idx_gmail_audit_log_event_type'), 'gmail_credential_audit_log', ['event_type'], unique=False)
    op.create_index(op.f('idx_gmail_audit_log_created_at'), 'gmail_credential_audit_log', ['created_at', 'task_id'], unique=False)
    op.create_table('failed_email_queue',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False, comment='Task that owns this email'),
    sa.Column('message_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Gmail message ID (unique per task)'),
    sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Email subject for audit trail'),
    sa.Column('sender', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Email sender for audit trail'),
    sa.Column('failure_reason', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Type of failure: auth_error | extraction_error | row_error | file_error'),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True, comment='Error message details'),
    sa.Column('error_count', sa.INTEGER(), autoincrement=False, nullable=False, comment='Number of times this email failed to process'),
    sa.Column('last_attempted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Timestamp of last retry attempt'),
    sa.Column('next_retry_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Scheduled time for next retry (respects exponential backoff)'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='When email was first marked as failed'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['task_id'], ['ingestion_tasks.id'], name=op.f('failed_email_queue_task_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('failed_email_queue_pkey')),
    sa.UniqueConstraint('task_id', 'message_id', name=op.f('uq_failed_email_task_message'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='Tracks email ingestion failures for retry with exponential backoff'
    )
    op.create_index(op.f('idx_failed_email_queue_task_next_retry'), 'failed_email_queue', ['task_id', 'next_retry_at'], unique=False)
    op.create_index(op.f('idx_failed_email_queue_created_at'), 'failed_email_queue', ['created_at'], unique=False)
    op.create_table('ingestion_deduplication',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('row_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cleaned_identifier', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('beast_uuid', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('is_duplicate', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('duplicate_of_run_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('dedup_action', sa.VARCHAR(length=50), server_default=sa.text("'first_occurrence'::character varying"), autoincrement=False, nullable=False),
    sa.Column('metrics_calculation_summary', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('is_connection_match', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_run_id'], ['ingestion_task_runs.id'], name=op.f('ingestion_deduplication_duplicate_of_run_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_task_runs.id'], name=op.f('ingestion_deduplication_run_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ingestion_deduplication_pkey'))
    )
    op.create_index(op.f('ix_ingestion_deduplication_is_duplicate'), 'ingestion_deduplication', ['is_duplicate'], unique=False)
    op.create_index(op.f('ix_ingestion_deduplication_beast_uuid'), 'ingestion_deduplication', ['beast_uuid'], unique=False)
    op.create_index(op.f('idx_ingestion_dedup_uuid'), 'ingestion_deduplication', ['beast_uuid'], unique=False)
    op.create_index(op.f('idx_ingestion_dedup_run_row'), 'ingestion_deduplication', ['run_id', 'row_number'], unique=False)
    op.create_index(op.f('idx_ingestion_dedup_is_dup'), 'ingestion_deduplication', ['is_duplicate'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('hmac_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('webhook_events_pkey'))
    )
    op.create_index(op.f('idx_webhook_events_source_type'), 'webhook_events', ['source', 'event_type'], unique=False)
    op.create_index(op.f('idx_webhook_events_processed_at'), 'webhook_events', ['processed_at'], unique=False)
    op.create_index(op.f('idx_webhook_events_event_id'), 'webhook_events', ['event_id'], unique=False)
    op.create_index(op.f('idx_webhook_events_created_at'), 'webhook_events', ['created_at'], unique=False)
    # ### end Alembic commands ###
